imx-atf: Deploy TF-A to normalized location
Build of imx-boot is failing:

```
| cp: cannot stat 'tmp/deploy/images/imx8qm-mek/bl31-imx8qm.bin-optee': No such file or directory
| WARNING: exit code 1 from a shell command.
ERROR: Task (bsp/meta-freescale/recipes-bsp/imx-mkimage/imx-boot_1.0.bb:do_compile) failed with exit code '1'
```

imx-boot expects TF-A at the top of the deploy folder.

https://github.com/Freescale/meta-freescale/commit/1ec9540091c6d2cb7faf679f3b01916bfb0a0397

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>