optee-os: Fix TA install and packaging
The base recipe doesn't handle usrmerge, which is enabled for AGL, leading to the
QA error:

```
ERROR: optee-os-3.17.0.imx-r0 do_package: QA Issue: optee-os: Files/directories were installed but not shipped in any package:
  /usr/lib/optee_armtz
  /usr/lib/optee_armtz/023f8f1a-292a-432b-8fc4-de8471358067.ta
  /usr/lib/optee_armtz/f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c.ta
  /usr/lib/optee_armtz/fd02c9da-306c-48c7-a49c-bbd827ae86ee.ta
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
optee-os: 4 installed and not shipped files. [installed-vs-shipped]
```

The base recipe also incorrectly installs to arch-specific lib. Fix the
install and update the packaging.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>